file_format: "1"
id: leelooo
name: Leelooo
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow

siblings:
  - leelooo_left
  - leelooo_right
  - leelooo_dongle
