file_format: "1"
id: ll
name: ll
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - ll_dongle
  - ll_left
  - ll_right
