manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/mstralenya
  projects:
    - name: zmk
      remote: zmk
      revision: leeloo_r2_branch
      import: app/west.yml
  self:
    path: config
