manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: zmkfix
      url-base: https://github.com/mstralenya
  projects:
    - name: zmk
      remote: zmkfix
      revision: leeloo
      import: app/west.yml
  self:
    path: config
